title: Tiffany Galicia
description: Professional Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
linkedin:
    url: https://www.linkedin.com/in/tiffany-galicia-288a091a8/
github:
    projects_url: https://github.com/tgalicia
docker:
    images_url: https://hub.docker.com/u/tgalicia
resume:
    url: ./Resume_TG_2020.docx

