title: Tiffany Galicia
description: Professional Portfolio
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://www.linkedin.com/in/tiffany-galicia-288a091a8/
  tar_url: https://github.com/tgalicia/tgalicia.github.io/Resume_TG_2020.docx
